### ISSUE TITLE
Skip the Not authenticated message when LOGNAME==='polyglot'

### ISSUE THREAD

**Issue by BenoitMercier** [pradeepmouli/udi-js#65]
The log currently shows this, even though process.env.LOGNAME==='polyglot'
2024-12-20 10:38:54 error: server: Not authenticated

**Comment by pradeepmouli** [comment]
"Authenticate" here means the plugin/socket client has authenticated with the server (i.e. is allowed to start the bridge). I.e. the plugin/socket client has sent an a message of the form {"type": auth, "credential": .....} which is passed to an authenticate function (which currently always returns true). If you send an any message like the above even {type: auth}, it will start. Though, probably the better approach would have been to authenticate on connect....

**Comment by pradeepmouli** [comment]
Just to clarify.... in theory you would want the authenticate, even if the service was started as polyglot....

**Comment by BenoitMercier** [comment]
Thanks for the clarification. But authenticate using what?  Until we have something, it would be preferable to not have this message as this would cause confusion for any user troubleshooting his setup.

**Comment by pradeepmouli** [comment]
well, the plugin already effectively verifies that end user is licensed, so only thing we need to authenticate is that socket client  _is_ the plugin.... and not something else.
